spring:
  output:
    ansi:
      enabled: DETECT

tom:
  maxConnections: 2000
  maxThreads: 2000
  soTimeout: 30000


#logging:
#  level:
#    root: ERROR
#    org.lili.forfun.spring.training: ERROR
#    org.springframework.web: ERROR

